Dockerfile, Jenkinsfile_CNP, Jenkinsfile_nightly, docker-compose.yml, package.json, src/test/cross-browser/runCrossBrowserTests.sh, src/test/cross-browser/supportedBrowsers.js
https://tools.hmcts.net/jira/browse/SIDM-6753
Display cross browser test reports correctly on Jenkins nightly build dashboard
```
[ ] Yes
[x] No
```
=> SIDM-6753 Display cross browser test reports correctly on Jenkins nightly build dashboard

Jenkinsfile_CNP, Jenkinsfile_nightly, config/custom-environment-variables.yaml
https://tools.hmcts.net/jira/browse/SIDM-6836
Pull smoke test username and password from Azure key vaults in Jenkins for tests
```
[ ] Yes
[x] No
```
=> SIDM-6836 Pull smoke test username and password from Azure key vaults in Jenkins for tests

src/main/modules/oidc/index.ts, src/main/views/redirect.njk
https://tools.hmcts.net/jira/browse/SIDM-6837
Fix 'Too many redirects' issue for slow IDAM login, e.g. example logging in using IDAM AAT or using CSRF protection
```
[ ] Yes
[x] No
```
=> Fix 'Too many redirects' issue for slow IDAM login

src/main/modules/oidc/index.ts
Fix access token not set when calling IDAM API
```
[ ] Yes
[ ] No
```
=> Fix access token not set when calling IDAM API

config/default.yaml, src/main/views/user-details.njk, src/test/functional/custom-steps.ts, src/test/functional/manage-users-test.ts, src/test/functional/search-user-test.ts, src/test/functional/steps.d.ts
https://tools.hmcts.net/jira/browse/SIDM-6823
search-user functional test
```
[ ] Yes
[x] No
```
=> Search-use functional test initial commit

charts/idam-user-dashboard/Chart.yaml, charts/idam-user-dashboard/values.yaml, config/custom-environment-variables.yaml, config/default.yaml, src/main/modules/health/index.ts, src/main/modules/properties-volume/index.ts, src/main/modules/session/index.ts
- Added redis host, port and pass
- Added redis healtcheck
```
[ ] Yes
[ ] No
```
=> enable_redis - Added redis cache hostname, port and pass

src/test/smoke/smoke.ts
- Changed health-check smoke test to individually check each required service
```
[ ] Yes
[x] No
```
=> Improved health-check smoke test

src/main/modules/oidc/index.ts, src/main/utils/urls.ts
- Removed ref to config in utils file
```
[ ] Yes
[x] No
```
=> fix-attempt-1

config/default.yaml, src/main/app.ts, src/main/modules/oidc/index.ts, src/main/modules/session/index.ts
https://tools.hmcts.net/jira/browse/SIDM-6603
- Fixed issue where logged out session issue
- Fixed issue with session-file-store logging errors when new session was generated on local-env
```
[ ] Yes
[x] No
```
=> SIDM-6603 - Ensured cookie was removed and fixed temp-file-store warning

package.json, src/main/HttpError.ts, src/main/app.ts, src/main/assets/scss/header.scss, src/main/assets/scss/main.scss, src/main/modules/csrf/index.ts, src/main/modules/error-handler/index.ts, src/main/modules/nunjucks/index.ts, src/main/modules/oidc/index.ts, src/main/views/add-users.njk, src/main/views/error.njk, src/main/views/macros/breadcrumb.njk, src/main/views/macros/csrf.njk, src/main/views/manage-users.njk, src/main/views/not-found.njk, src/main/views/template.njk, src/main/views/user-details.njk, src/main/views/user-option.njk, yarn.lock
- Right aligned  'sign-out' button on banner
- Fixed thrown error handler not actually handling thrown errors (not rendering error.njk template)
- Added prettier error pages
- Fixed issue where csrf token wasn't being inserted into forms or checked
```
[ ] Yes
[x] No
```
=> CSRF, banner and error page fixes

src/test/config.ts, src/test/functional/shared/apiHelpers.ts
https://tools.hmcts.net/jira/browse/SIDM-7072
Added methods to apiHelper for OIDCToken and suspendUser
```
[ ] Yes
[x] No
```
=> Added methods to apiHelper for OIDCToken and suspendUser

src/test/functional/error-page-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7080
Added Error Page tests for status codes 403 & 404
```
[ ] Yes
[x] No
```
=> Added Error Page tests for status codes 403 & 404

package.json, yarn.lock
- Patch CVE-2022-0536 by upgrading axios
```
[ ] Yes
[x] No
```
=> CVE-2022-0536 - Upgrade axios

charts/idam-user-dashboard/Chart.yaml
- Upgrade chart-nodejs to 2.4.0
```
[ ] Yes
[x] No
```
=> Upgrade chart-nodejs version

src/main/app/idam-api/IdamApi.ts, src/main/controllers/RootController.ts, src/main/controllers/UserResultsController.ts, src/main/interfaces/PageData.ts, src/main/modules/awilix/index.ts, src/main/modules/oidc/index.ts, src/main/utils/urls.ts, src/main/views/manage-users.njk, src/main/views/user-details.njk, src/test/unit/test/app/idam-api/IdamAPI.ts, src/test/unit/test/controllers/AddUsersController.ts, src/test/unit/test/controllers/ManageUsersController.ts, src/test/unit/test/controllers/RootController.ts, src/test/unit/test/controllers/UserOptionController.ts, src/test/unit/test/controllers/UserResultsController.ts
- Updated URL format to fit `/users/ACTION` format
- `/add-users` -> `/users/add`
- `/manage-users `-> `/users/manage`
- `/user-details` -> `/users/details`
- etc.
- Added URL variables into PageContent by default, updated forms/links to make use of these.
- Changed IdamApi class to be used through DI rather than through accessing the class through req.local...scope.
```
[ ] Yes
[x] No
```
=> Updated URL format and added URLs to page content, updated IdamApi class to use DI

src/main/app.ts
- Moved AppInsights setup to run before Awilix container setup, otherwise telementryClient could be undefined in container.
```
[ ] Yes
[x] No
```
=> Moved AppInsights to enable before Awilix container setup

src/test/functional/search-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7173
Added functional tests for search by sso-id and user-id
```
[ ] Yes
[x] No
```
=> Functional tests for search by sso-id and user-id

src/main/assets/scss/button.scss, src/main/assets/scss/main.scss, src/main/views/manage-users.njk, src/main/views/user-details.njk
https://tools.hmcts.net/jira/browse/SIDM-6940
- Reorder the edit user page as per screenshot
- Edit and suspend left aligned. with delete right aligned
- Edit button is green, suspend button is grey, delete button is red
- Back using backlink
```
[ ] Yes
[x] No
```
=> SIDM-6940 - Update UI for user details page

config/default.yaml, src/main/modules/oidc/index.ts, src/test/config.ts, src/test/functional/edit-user-test.ts, src/test/functional/error-page-test.ts, src/test/functional/manage-users-test.ts, src/test/functional/search-user-test.ts, src/test/functional/sign-in-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7202
- Added check for `idam-user-dashboard--access` role
- Updated functional tests so that logged in user has `idam-user-dashboard--access`
- Added functional test for testing if user without access role can still access service.
```
[ ] Yes
[x] No
```
=> SIDM-7202 - Restricted idam-user-dashboard to specific role

src/test/functional/sign-in-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7203
Added negative test for role based access
```
[ ] Yes
[x] No
```
=> Added negative test for role based access

src/main/routes.ts, src/main/views/user-option.njk, src/test/functional/edit-user-test.ts, src/test/functional/manage-users-test.ts, src/test/functional/search-user-test.ts
- Wrapped 'add users' feature with beta feature flag
- Updated tests to remove watching for 'add users' text
```
[ ] Yes
[x] No
```
=> Hide 'add users' behind beta feature flag

src/main/controllers/UserEditController.ts, src/test/functional/delete-user-test.ts, src/test/functional/edit-user-test.ts, src/test/functional/error-page-test.ts, src/test/functional/manage-users-test.ts, src/test/functional/search-user-test.ts, src/test/functional/shared/random-data.ts, src/test/functional/sign-in-user-test.ts, src/test/functional/suspend-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7211
Added edit user validation scenarios 
Sorted random-test data
Moved tags to the end of scenarios 
```
[ ] Yes
[x] No
```
=> SIDM-7211 - Added functional testing for edit user

src/main/app/feature-flags/flags.ts, src/main/controllers/RootController.ts, src/main/interfaces/PageData.ts, src/main/routes.ts, src/main/views/user-details.njk, src/main/views/user-option.njk, src/test/functional/delete-user-test.ts, src/test/functional/edit-user-test.ts, src/test/functional/manage-users-test.ts, src/test/functional/suspend-user-test.ts, src/test/unit/test/controllers/RootController.ts
https://tools.hmcts.net/jira/browse/SIDM-7290
- Wrapped each beta feature within its own feature flag
```
[ ] Yes
[x] No
```
=> SIDM-7290 - Wrapped each beta feature in its own flag

src/main/views/add-user-roles.njk, src/main/views/macros/roleList.njk
- Added ability to set searchBox ID on a roleList component
```
[ ] Yes
[x] No
```
=> SIDM-7124 - Added search box ID for roleList

src/main/views/add-user-completion.njk, src/main/views/add-user-details.njk, src/main/views/add-user-roles.njk, src/main/views/add-users.njk, src/main/views/delete-user-successful.njk, src/main/views/delete-user.njk, src/main/views/edit-user.njk, src/main/views/error.njk, src/main/views/manage-users.njk, src/main/views/suspend-user-successful.njk, src/main/views/suspend-user.njk, src/main/views/un-suspend-user-successful.njk, src/main/views/un-suspend-user.njk, src/main/views/user-details.njk, src/main/views/user-option.njk
- Added titles to pages
```
[ ] Yes
[x] No
```
=> Added titles to pages

src/main/assets/scss/roleList.scss, src/main/utils/roleUtils.ts, src/test/unit/test/controllers/UserEditController.ts, src/test/unit/test/utils/roleUtils.ts
https://tools.hmcts.net/jira/browse/SIDM-7112
- Sort assignable roles to the top on edit user page.
- Make role list scrollbar disappear for small role list.
```
[ ] Yes
[x] No
```
=> SIDM-7112 Update role list appearance of Edit User screen

src/main/app/idam-api/IdamAPI.ts, src/main/controllers/AddUserDetailsController.ts, src/main/controllers/UserResultsController.ts, src/test/unit/test/app/idam-api/IdamAPI.ts, src/test/unit/test/controllers/AddUserDetailsController.ts, src/test/unit/test/controllers/AddUserRolesController.ts, src/test/unit/test/controllers/UserResultsController.ts, src/test/unit/utils/mockApi.ts
Add specific search by email and SSO ID methods
```
[ ] Yes
[x] No
```
=> Add specific search by email and SSO ID methods

src/test/functional/edit-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7354
Added edit role scenario
```
[ ] Yes
[x] No
```
=> Added edit-roles functional test

src/main/app/idam-api/IdamAPI.ts, src/main/controllers/UserEditController.ts, src/main/controllers/UserResultsController.ts, src/main/interfaces/User.ts, src/main/utils/roleUtils.ts, src/main/views/edit-user.njk, src/main/views/user-details.njk, src/test/unit/test/controllers/UserEditController.ts, src/test/unit/test/controllers/UserResultsController.ts, src/test/unit/test/utils/roleUtils.ts
https://tools.hmcts.net/jira/browse/SIDM-6919
Add multi-factor authentication flag for idam-mfa-disabled user role
```
[ ] Yes
[x] No
```
=> SIDM-6919 Add multi-factor authentication flag for idam-mfa-disabled user role

src/main/app/idam-api/IdamAPI.ts, src/main/controllers/AddPrivateBetaServiceController.ts, src/main/controllers/AddUserDetailsController.ts, src/main/controllers/AddUserRolesController.ts, src/main/interfaces/PrivateBetaService.ts, src/main/interfaces/services.ts, src/main/modules/awilix/index.ts, src/main/modules/nunjucks/index.ts, src/main/routes.ts, src/main/utils/error.ts, src/main/utils/serviceUtils.ts, src/main/utils/urls.ts, src/main/utils/utils.ts, src/main/views/add-user-details.njk, src/main/views/add-user-private-beta-service.njk, src/main/views/add-user-roles.njk, src/test/a11y/a11y.ts, src/test/functional/register-user-test.ts, src/test/functional/shared/helpers/testingSupportApiHelper.ts, src/test/functional/shared/random-data.ts, src/test/functional/shared/testingSupportApi.ts, src/test/unit/test/controllers/AddPrivateBetaServiceController.ts, src/test/unit/test/controllers/AddUserDetailsController.ts, src/test/unit/test/controllers/AddUserRolesController.ts, src/test/unit/test/utils/roleUtils.ts, src/test/unit/test/utils/serviceUtils.ts, src/test/unit/test/utils/utils.ts
https://tools.hmcts.net/jira/browse/SIDM-6594
Enable registration of new users with private beta citizen roles
```
[ ] Yes
[x] No
```
=> SIDM-6594 Enable registration of new users with private beta citizen roles

src/main/controllers/AddUserDetailsController.ts, src/main/views/add-user-details.njk, src/test/unit/test/controllers/AddUserDetailsController.ts
https://tools.hmcts.net/jira/browse/SIDM-6594
Disable 'Citizen' option during user registration if the logged in user does not have the assignable role of 'citizen'
```
[ ] Yes
[ ] No
```
=> SIDM-6594 Disable 'Citizen' option during user registration if the logged in user does not have the assignable role of 'citizen'

src/main/app/feature-flags/flags.ts, src/main/routes.ts, src/main/views/add-user-details.njk, src/main/views/edit-user.njk, src/main/views/template.njk, src/test/functional/edit-user-test.ts, src/test/functional/register-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7623
- Wrapped MFA and private-beta-citizen with gamma feature flags
- Updated phase banner to say 'Beta'
```
[ ] Yes
[x] No
```
=> SIDM-7623 - Wrap gamma features with feature flags

src/main/app/idam-api/IdamAPI.ts
https://tools.hmcts.net/jira/browse/SIDM-7676
```
[ ] Yes
[x] No
```
=> SIDM-7676 - Added conditional for checking if rolesmap has role

src/main/views/edit-user.njk, src/test/functional/edit-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7678
- Enabled search box on roles list component on the edit user page
```
[ ] Yes
[x] No
```
=> SIDM-7678 - Activated roles searchbox on edit user page

src/main/app/feature-flags/flags.ts, src/main/controllers/UserResultsController.ts, src/main/interfaces/User.ts, src/main/routes.ts, src/main/utils/utils.ts, src/main/views/user-details.njk, src/test/unit/test/controllers/UserResultsController.ts, src/test/unit/test/utils/utils.ts
https://tools.hmcts.net/jira/browse/SIDM-6938
Show warning message for locked users in user details page
```
[ ] Yes
[x] No
```
=> SIDM-6938 Show warning message for locked users in user details page

charts/idam-user-dashboard/Chart.yaml, src/test/functional/delete-user-test.ts, src/test/functional/remove-SSO-ID-test.ts
https://tools.hmcts.net/jira/browse/SIDM-7178
Added functional tests for remove-sso from user
```
[ ] Yes
[x] No
```
=> Added functional tests for remove-sso from user

src/main/assets/scss/main.scss, src/main/assets/scss/table.scss, src/main/views/view-report.njk
https://tools.hmcts.net/jira/browse/SIDM-7647
Hide report table on report details page for mobile devices
```
[ ] Yes
[x] No
```
=> SIDM-7647 Hide report table on report details page for mobile devices

src/main/views/manage-user.njk
https://tools.hmcts.net/jira/browse/SIDM-7649
Removed unnecessary H1 on manage users page
```
[ ] Yes
[x] No
```
=> SIDM-7649 - Removed extra H1 on manage users page

src/main/views/manage-user.njk
https://tools.hmcts.net/jira/browse/SIDM-7649
Updated search page headers
```
[ ] Yes
[x] No
```
=> SIDM-7649 - Updated search page headers

src/test/functional/custom-steps.ts, src/test/functional/delete-user-test.ts, src/test/functional/lock-account-test.ts, src/test/functional/suspend-user-test.ts
- Added new custom step for logging out, adding wait for 'Sign in' text before trying sign in function
```
[ ] Yes
[x] No
```
=> Added new custom step for logging out

src/main/app/idam-api/IdamAPI.ts, src/test/unit/test/app/idam-api/IdamAPI.ts
https://tools.hmcts.net/jira/browse/SIDM-8288
remove timestamp from search query
```
[ ] Yes
[X] No
```
=> remove timestamp from search query

charts/idam-user-dashboard/Chart.yaml
=> Bump chart version

src/test/config.ts, src/test/cross-browser/saucelabs.conf.ts, src/test/functional/custom-steps.ts, src/test/tsconfig.json
https://tools.hmcts.net/jira/browse/SIDM-8453
```
[ ] Yes
[ ] No
```
=> Sidm 8453 test fix

src/test/functional/custom-steps.ts
=> SIDM-8453 Added wait

src/test/config.ts, src/test/functional/custom-steps.ts
https://tools.hmcts.net/jira/browse/SIDM-8453
```
[ ] Yes
[ ] No
```
=> Sidm 8453 intermittent test failure fix

config/default.yaml, package.json, src/main/app.ts, src/main/app/idam-auth/IdamAuth.ts, src/main/app/idam-auth/OIDCToken.ts, src/main/controllers/AddPrivateBetaServiceController.ts, src/main/controllers/AddUserDetailsController.ts, src/main/controllers/AddUserRolesController.ts, src/main/controllers/RootController.ts, src/main/controllers/UserEditController.ts, src/main/controllers/UserResultsController.ts, src/main/interfaces/AuthedRequest.ts, src/main/modules/awilix/index.ts, src/main/modules/csrf/index.ts, src/main/modules/oidc/index.ts, src/main/modules/session/index.ts, src/main/views/template.njk, src/test/functional/sign-in-user-test.ts, src/test/unit/test/app/idam-auth/IdamAuth.ts, src/test/unit/test/controllers/AddPrivateBetaServiceController.ts, src/test/unit/test/controllers/AddUserDetailsController.ts, src/test/unit/test/controllers/AddUserRolesController.ts, src/test/unit/test/controllers/RootController.ts, src/test/unit/test/controllers/UserEditController.ts, src/test/unit/test/controllers/UserResultsController.ts, yarn.lock
Reverts hmcts/idam-user-dashboard#311
=> Revert "SIDM-7454 - Replaced OIDC setup with express-openid-connect"

src/test/unit/test/controllers/UserResultsController.ts
=> SIDM-6605-Added tests in UserResultsController.ts

.github/dependabot.yml, .github/renovate.json
https://tools.hmcts.net/jira/browse/SIDM-8846
* Remove dependabot
* Use basic renovate config
```
[ ] Yes
[x] No
```
=> Remove dependabot plus renovate config

charts/idam-user-dashboard/Chart.yaml
https://tools.hmcts.net/jira/browse/SIDM-8935
Upgrade to chart-nodejs v3.0.0.
```
[ ] Yes
[x] No
```
=> Update base chart-nodejs

yarn.lock
Reverts hmcts/idam-user-dashboard#625
=> Revert "Update dependency playwright to v1.38.1"

src/main/controllers/DownloadReportController.ts
It seems the issue is that the Ref for the error message references something that does not exist and that is a problem for pally.
=> Fix pally test issue

src/test/a11y/a11y.ts, src/test/functional/codecept.conf.ts, src/test/functional/generate-user-report-test.ts, src/test/functional/manage-users-test.ts, src/test/functional/shared/helpers/testingSupportApiHelper.ts, src/test/functional/shared/testingSupportApi.ts
https://tools.hmcts.net/jira/browse/SIDM-8984
Remove old teardown
```
[ ] Yes
[x] No
```
=> SIDM-8984 Remove old teardown

src/test/cross-browser/saucelabs.conf.ts, src/test/functional/register-user-test.ts
https://tools.hmcts.net/jira/browse/SIDM-8984
cross browser tests
```
[ ] Yes
[x] No
```
=> SIDM-8984 cross browser tests

src/test/functional/custom-steps.ts
https://tools.hmcts.net/jira/browse/SIDM-8984
check login worked
```
[ ] Yes
[x] No
```
=> SIDM-8984 check login worked

.github/renovate.json
https://tools.hmcts.net/jira/browse/SIDM-8984
Change renovate schedule to afternoon to avoid clashes with nightly tests running in morning.
```
[ ] Yes
[X] No
```
=> SIDM-8984 Change renovate schedule to afternoon

src/main/modules/appinsights/index.ts
N/A
Set sampling percentage to 100 for Dashboard's `/callback` endpoint, so that we get all logs related to the authentication journey.
```
[ ] Yes
[x] No
```
=> Do not lose telemetry for sign-ins

audit.json
=> SIDM-8920 fix audit issue

audit.json
N/A
Suppress a vulnerability reported by ZAP as it is not critical.
```
[ ] Yes
[x] No
```
=> Suppress 10096_Timestamp_Disclosure

src/main/modules/helmet/index.ts, src/main/views/macros/roleList.njk, src/test/functional/edit-user-test.ts
=> Hide roles I cant assign

src/test/v2/common/dao/SetupDao.ts, src/test/v2/cross-browser/saucelabs.conf.ts
N/A
Fix cross browser tests by having an admin per worker
```
[ ] Yes
[x] No
```
=> admins per worker

src/test/v2/common/factories/users.ts, src/test/v2/functional/register_private_beta_citizen_test.ts, src/test/v2/functional/sign_in_test.ts
Fix user passwords
```
[ ] Yes
[x] No
```
=> SIDM-9057 fix password in tests

src/test/v2/functional/delete_user_test.ts
add see after click
```
[ ] Yes
[X] No
```
=> SIDM-9057 add see after click

src/test/v2/common/steps_file.ts, src/test/v2/functional/delete_user_test.ts, src/test/v2/functional/edit_user_remove_sso_test.ts, src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/generate_user_report_test.ts, src/test/v2/functional/register_private_beta_citizen_test.ts, src/test/v2/functional/search_user_test.ts, src/test/v2/functional/sign_in_test.ts, src/test/v2/functional/suspend_user_test.ts, src/test/v2/functional/view_user_test.ts
Stabilise
```
[ ] Yes
[x] No
```
=> SIDM-9057 check user gets created

src/test/v2/common/steps_file.ts, src/test/v2/functional/delete_user_test.ts, src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/generate_user_report_test.ts, src/test/v2/functional/register_private_beta_citizen_test.ts, src/test/v2/functional/register_user_test.ts
Check creation of roles and services
```
[ ] Yes
[X] No
```
=> SIDM-9057 check creation of roles and services

src/test/v2/common/factories/roles.ts, src/test/v2/common/factories/services.ts
uniqueness for role and service names
```
[ ] Yes
[X] No
```
=> SIDM-9057 uniqueness for role and service names

src/main/interfaces/User.ts, src/main/modules/oidc/index.ts
Add oidc callback logging
```
[ ] Yes
[X] No
```
=> SIDM-9057 add logging

src/main/modules/oidc/index.ts, src/test/v2/common/factories/roles.ts
better logging
```
[ ] Yes
[x] No
```
=> SIDM-9057 better logging

package.json, yarn.lock
N/A
Upgrade ip to 1.1.9
```
[ ] Yes
[x] No
```
=> CVE-2023-42282: Fix a vulnerability in ip:1.1.8

src/test/v2/README.md
Add readme
```
[ ] Yes
[x] No
```
=> add readme

src/test/v2/common/steps_file.ts
N/A
retry click
```
[ ] Yes
[X] No
```
=> retry click

package.json, yarn.lock
=> Dependency check fixes.

src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/register_user_test.ts
https://tools.hmcts.net/jira/browse/SIDM-9208
Uncheck hide roles before applying filter
```
[ ] Yes
[x] No
```
=> SIDM-9208 uncheck hidden

src/main/controllers/UserResultsController.ts, src/main/views/user-details.njk, src/test/unit/utils/mockRequest.ts
So basically if you arrived there from somewhere else, its safe to assume you arrived there from the search.
Otherwise there will be no button.
=> SIDM-8398 Remove return to search button

src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/register_user_test.ts
N/A
wait after filtering roles
```
[ ] Yes
[X] No
```
=> wait after filtering roles

src/main/controllers/ViewReportController.ts, src/main/utils/error.ts, src/main/views/view-report.njk
If there are no results for that page, remove next, leave back and explain why its empty
=> SIDM-8981 Explain empty page

src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/register_user_test.ts
https://tools.hmcts.net/jira/browse/SIDM-9272
Filter specific role before whole list
```
[ ] Yes
[X] No
```
=> SIDM-9272 filter specific role before whole list

config/default.yaml, src/main/controllers/UserResultsController.ts, src/test/unit/test/controllers/UserResultsController.ts
https://tools.hmcts.net/jira/browse/SIDM-9290
Get lock duration from config
```
[ ] Yes
[ ] No
```
=> SIDM-9290 Get lock duration from config

src/main/app.ts, src/main/app/authorized-axios/AuthorizedAxios.ts, src/main/controllers/ManageUserController.ts, src/main/controllers/UserResultsController.ts, src/main/modules/awilix/index.ts, src/main/modules/oidc/index.ts
https://tools.hmcts.net/jira/browse/SIDM-9303
Add app insight exception handling to axios calls, and use console.log with more detailed messages.
```
[ ] Yes
[X] No
```
=> SIDM-9303 more logging

src/main/controllers/UserResultsController.ts, src/main/modules/oidc/index.ts
https://tools.hmcts.net/jira/browse/SIDM-9304
More logging
```
[ ] Yes
[X] No
```
=> SIDM-9304 more logging

src/main/modules/error-handler/index.ts
https://tools.hmcts.net/jira/browse/SIDM-9304
Log not found
```
[ ] Yes
[x] No
```
=> SIDM-9304 log not found

src/main/controllers/UserResultsController.ts, src/main/modules/error-handler/index.ts, src/main/modules/oidc/index.ts
https://tools.hmcts.net/jira/browse/SIDM-9304
Log fixes.
Also set timeout for client credential/password grant token calls
```
[ ] Yes
[X] No
```
=> SIDM-9304 log fixes

src/test/v2/common/shared_config.ts, src/test/v2/common/steps_file.ts
N/A
Look for bad gateways in tests.
the tryTo function lets you execute steps that can fail. I'm using it here to reload the current page if we end up on a Bad Gateway result.
```
[ ] Yes
[X] No
```
=> Look for bad gateways

package-lock.json, yarn.lock
Reverts hmcts/idam-user-dashboard#889
=> Revert "Update dependency awilix to v10.0.2"

charts/idam-user-dashboard/Chart.yaml, charts/idam-user-dashboard/values.yaml
N/A
The application is struggling to deploy -  we will give it more CPU to see if that helps.
```
[ ] Yes
[x] No
```
=> Increase devCpuLimits an devCpuRequests

src/main/modules/health/index.ts, src/test/v2/common/factories/services.ts, src/test/v2/common/shared_config.ts, src/test/v2/common/steps_file.ts
=> SIDM-9380 tweaks

src/test/v2/functional/delete_user_test.ts, src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/register_user_test.ts
Wait for visible
```
[ ] Yes
[X] No
```
=> SIDM-9380 wait for visible

src/test/v2/common/shared_config.ts, src/test/v2/functional/edit_user_remove_sso_test.ts, src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/generate_user_report_test.ts, src/test/v2/functional/register_private_beta_citizen_test.ts, src/test/v2/functional/register_user_test.ts, src/test/v2/functional/search_user_test.ts, src/test/v2/functional/sign_in_test.ts, src/test/v2/functional/suspend_user_test.ts
Add more awaits to ensure everything runs in sequence
```
[ ] Yes
[X] No
```
=> SIDM-9380 await more

src/test/v2/common/steps_file.ts
Await even more
```
[ ] Yes
[X] No
```
=> SIDM-9380 await even more

src/test/v2/common/steps_file.ts, src/test/v2/functional/register_private_beta_citizen_test.ts
More awaits
```
[ ] Yes
[X] No
```
=> SIDM-9380 more awaits

config/custom-environment-variables.yaml, config/default.yaml, package-lock.json, package.json, src/main/app.ts, src/main/app/idam-api/IdamAPI.ts, src/main/app/invite-service/InviteService.ts, src/main/app/reports/ReportsHandler.ts, src/main/app/service-provider-service/ServiceProviderService.ts, src/main/controllers/DownloadReportController.ts, src/main/modules/appinsights/index.ts, src/main/modules/awilix/index.ts, src/main/modules/error-handler/index.ts, src/main/modules/logging/index.ts, src/main/modules/oidc/index.ts, src/main/server.ts, src/main/typing/@hmcts/nodejs-logging.d.ts, src/test/unit/test/app/idam-api/IdamAPI.ts, src/test/unit/test/app/invite-service/InviteService.ts, src/test/unit/test/app/reports/ReportsHandler.ts, src/test/unit/test/app/service-provider-service/ServiceProviderService.ts, src/test/unit/test/controllers/DownloadReportController.ts, src/test/unit/utils/mockLogger.ts, yarn.lock
https://tools.hmcts.net/jira/browse/SIDM-9399
Use winston logging. In this setup winston is logging to Console, and app insights is then picking up on the console messages. There are other ways to integreate winston and app insights but this is nice and simple.
```
[ ] Yes
[X] No
```
=> SIDM-9399 use winston logging

src/test/v2/functional/edit_user_test.ts
more awaits
```
[ ] Yes
[X] No
```
=> SIDM-9380 more awaiting

src/test/v2/functional/delete_user_test.ts, src/test/v2/functional/edit_user_remove_sso_test.ts, src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/register_user_test.ts, src/test/v2/functional/suspend_user_test.ts
confirm checkbox changes
```
[ ] Yes
[X] No
```
=> SIDM-9380 confirm checkbox changes

src/test/v2/common/factories/users.ts, src/test/v2/common/steps_file.ts, src/test/v2/functional/edit_user_test.ts
try creating users again
```
[ ] Yes
[X] No
```
=> SIDM-9380 try creating users again

src/main/modules/health/index.ts
N/A
Fix healthcheck logging
```
[ ] Yes
[x] No
```
=> Fix healthcheck logging

config/custom-environment-variables.yaml, config/default.yaml, src/main/modules/health/index.ts
N/A
configurable healthcheck
```
[ ] Yes
[X] No
```
=> configurable healthcheck

src/test/v2/common/steps_file.ts, src/test/v2/functional/edit_user_test.ts
More retries
```
[ ] Yes
[X] No
```
=> SIDM-9380 retries

package.json, yarn.lock
N/A
Fixed dependencies. Upgraded cookie version.
```
[ ] Yes
[X] No
```
=> Fixed dependencies. Upgraded cookie version.

src/main/assets/js/RoleList.js
Reverts hmcts/idam-user-dashboard#913
=> Revert "Try fix role search again"

src/test/v2/common/steps_file.ts, src/test/v2/functional/register_user_test.ts
Filter for pending invites in test. Need to add this since there's no current cleanup process for expired invites and faker has a tendency to produce the same email address every once in a while.
```
[ ] Yes
[X] No
```
=> SIDM-9380 Filter for pending invites and other fixes

src/test/v2/common/steps_file.ts, src/test/v2/functional/register_private_beta_citizen_test.ts, src/test/v2/functional/sign_in_test.ts
Support
Add retries, and standardise methods with idam-hmcts-access
```
[ ] Yes
[X] No
```
=> Add retry and standardise methods

src/test/v2/accessibility/accessibility_test.ts, src/test/v2/common/steps_file.ts, src/test/v2/functional/delete_user_test.ts, src/test/v2/functional/edit_user_remove_sso_test.ts, src/test/v2/functional/edit_user_test.ts, src/test/v2/functional/register_private_beta_citizen_test.ts, src/test/v2/functional/register_user_test.ts, src/test/v2/functional/suspend_user_test.ts, src/test/v2/functional/view_user_test.ts
Jump to pages
```
[ ] Yes
[X] No
```
=> jump to pages

src/test/v2/common/steps_file.ts, src/test/v2/functional/register_private_beta_citizen_test.ts, src/test/v2/functional/register_user_test.ts
Alternative retry using back button
```
[ ] Yes
[X] No
```
=> SIDM-9547 alternative retry

src/test/v2/common/steps_file.ts
Log retry details
```
[ ] Yes
[X] No
```
=> SIDM-9547 Log retry details

src/test/v2/common/steps_file.ts
More failed logs
```
[ ] Yes
[X] No
```
=> SIDM-9547 more failed logs

src/test/v2/cross-browser/saucelabs.conf.ts, src/test/v2/functional/codecept.conf.ts
Add retries for functional and cross browser tests.
```
[ ] Yes
[x] No
```
=> SIDM-9547 Add retries for functional and cross browser tests.

src/test/v2/functional/edit_user_test.ts
https://tools.hmcts.net/jira/browse/SIDM-9476
Add test to ensure existing roles are unchanged after adding a filtered role.
```
[ ] Yes
[X] No
```
=> SIDM-9467 filtered roles test

src/test/v2/functional/edit_user_test.ts
https://tools.hmcts.net/jira/browse/SIDM-9360
Added functional tests
```
[ ] Yes
[X] No
```
=> SIDM-9360 functional tests

yarn-audit-known-issues
https://tools.hmcts.net/jira/browse/SIDM-9790
Change to audit message
```
[ ] Yes
[X] No
```
=> SIDM-9790 change to audit message

charts/idam-user-dashboard/Chart.yaml, charts/idam-user-dashboard/values.yaml, src/test/v2/common/steps_file.ts, src/test/v2/functional/sign_in_test.ts
https://tools.hmcts.net/jira/browse/SIDM-9822
Use hmcts-access for dashboard logins by default
```
[ ] Yes
[X] No
```
=> SIDM-9822 use hmcts-access for dashboard logins by default

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/SIDM-9937
added hmcts-access to zap ignore in the nightly file
```
[ ] Yes
[X] No
```
=> Update Jenkinsfile_nightly to ignore hmcts access
