hmcts/idam-user-dashboard

package.json, yarn.lock
- Upgradde follow-redirects to higher version to patch CVE-2022-0155 exploit
```
[ ] Yes
[x] No
```
=> CVE-2022-0155 patch

Jenkinsfile_nightly
- Updated to use other style of accessing env variable.
```
[ ] Yes
[x] No
```
=> Fix for nightly builds due to PARAMS.ENVIROMENT not existing

src/main/utils/utils.ts, src/test/unit/test/utils/utils.ts
Add IDAM_SYSTEM_OWNER to default role for sorting in the user results screen
```
[ ] Yes
[x] No
```
=> Add IDAM_SYSTEM_OWNER to default role for sorting in the user results screen

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/SIDM-6753
- Added TEST_URL environment variable which should point to AAT url on nightly builds
```
[ ] Yes
[x] No
```
=> SIDM-6753 - Added TEST_URL variable to nightly build

src/main/modules/session/index.ts
- Renamed session cookie from 'idam-session' to 'idam-user-dashboard-session' for clarity.
```
[ ] Yes
[x] No
```
=> Updated idam-session cookie to idam-user-dashboard-session

package.json, yarn.lock
- Updated node-fetch dependency due to CVE-2022-0235
- Updated axios to 0.25.0 and removed resolution for follow-redirects dependency
```
[ ] Yes
[x] No
```
=> CVE-2022-0235 - Updated node-fetch dependency

.sass-lint.yml, package.json, yarn.lock
- Recreated PR due to deployment issues
- CVE-2022-0144 / CVE-2020-28499 / CVE-2021-23807 - Removed unused sass-lint
```
[ ] Yes
[x] No
```
=> CVE-2022-0144 / CVE-2020-28499 / CVE-2021-23807 - Removed sass-lint

src/main/controllers/UserResultsController.ts, src/main/routes.ts, src/main/views/manage-users.njk, src/test/unit/test/controllers/UserResultsController.ts
- Suggestion from @kremi on potentonal security issue where user email is exposed in UserResultsController requests.
- Switched to sending email data in POST rather than GET
```
[ ] Yes
[X] No
```
=> Switch from a GET to a POST for user-results due to security

src/main/modules/helmet/index.ts
- Sets useDefaults back to false, just like in helmet 4.6.0, fixes issue where assets/links are served incorrectly on local instance, especially when running cross-browser tests
```
[ ] Yes
[x] No
```
=> Fix Safari on local env / Helmet to not use defaults option

src/main/controllers/RootController.ts, src/main/controllers/UserResultsController.ts, src/main/modules/error-handler/asyncErrorDecorator.ts
- Added class/method decorator `@asyncError` which will wrap a method/methods of a class with try/catch block to allow Express to handle thrown errors in async code. 
```
[ ] Yes
[x] No
```
=> async-error-wrap - Added asyncError class/method decorator

Jenkinsfile_nightly, src/test/functional/shared/helpers/featureFlagHelper.ts
- Archive nightly build artifacts so we can easily collect and build a big report of stability over time
- Added thread/worker ID to skipped test message in case issue occurs on thread (makes it easier to follow)
```
[ ] Yes
[x] No
```
=> Small changes

src/main/controllers/UserActionsController.ts, src/main/controllers/UserEditController.ts, src/main/modules/awilix/index.ts, src/main/routes.ts, src/main/utils/urls.ts, src/main/views/edit-user.njk, src/test/unit/test/controllers/UserActionsController.ts, src/test/unit/test/controllers/UserEditController.ts, src/test/unit/utils/mockRootController.ts
- Updated edit user to not be inside UserActionsController but instead inside UserEditController, in-line with how it's done for user delete.
```
[ ] Yes
[x] No
```
=> edit-user - Updated edit user to match delete user controller style

src/test/functional/shared/testingSupportApi.ts
- Provided async argument to `/testing-support/test-data` due to connection timing out before test-data is all cleared.
```
[ ] Yes
[x] No
```
=> Changed deleteAllTestData to use async

package.json, yarn.lock
Update version for miminist dependency to fix security vulnerability CVE-2021-44906
```
[ ] Yes
[x] No
```
=> CVE-2021-44906 Update version for miminist dependency to fix security vulnerability

src/main/modules/helmet/index.ts, src/main/views/template.njk
- Fixed helmet to allow for unsafe-eval/unsafe-inline on development builds. Webpack uses 'eval' for creating sourcemaps etc. on local development builds, and this stops the JS from being executed correctly on local.
-Removed unused Google Analytics code
```
[ ] Yes
[x] No
```
=> Fixed helmet and removed unused GA stuff

src/test/unit/test/controllers/AddUserDetailsController.ts, src/test/unit/test/controllers/AddUserRolesController.ts, src/test/unit/test/controllers/AddUsersController.ts, src/test/unit/test/controllers/ManageUserController.ts, src/test/unit/test/controllers/UserOptionController.ts, src/test/unit/utils/mockRootController.ts
- Updated old/outdated unit tests to use the recently introduced mockRootController
```
[ ] Yes
[x] No
```
=> Cleanup unit tests - Updated old unit tests to use mockRootController

package.json, yarn.lock
Reverts hmcts/idam-user-dashboard#263
Upgrading has broken cross-browser tests in the build env as the builder is missing required dependencies.
=> Revert "Bump playwright from 1.19.2 to 1.20.1"

src/main/app/idam-api/IdamAPI.ts, src/main/app/idam-auth/IdamAuth.ts, src/main/app/idam-auth/OIDCToken.ts, src/main/modules/oidc/index.ts, src/test/unit/test/app/idam-api/IdamAPI.ts, src/test/unit/test/app/idam-auth/IdamAuth.ts
https://tools.hmcts.net/jira/browse/SIDM-7622
- Added function to build /o/endSession endpoint redirect when a user is logging out
- Fixed issue with some unit tests 
- Added unit tests for un-covered IdamAuth
```
[ ] Yes
[x] No
```
=> SIDM-7622 - Re-added use of /o/endSession for logging out

src/main/views/generate-report.njk, src/main/views/view-report.njk
- Added warning about 500 user limit on generated reports
- Fixed incorrect breadcrumb string
```
[ ] Yes
[x] No
```
=> Added 500 user limit warning and fixed incorrect string

package.json, src/main/views/manage-user.njk, yarn.lock
- Upgraded to
@hmcts/nodejs-healthcheck: 1.7.3,
@hmcts/nodejs-logging: 4.0.4,
@hmcts/properties-volume: 0.0.14
```
[ ] Yes
[x] No
```
=> CVE fixes - Upgrade nodejs-logging and nodejs-healthcheck

src/main/controllers/UserResultsController.ts, src/main/views/user-details.njk, src/main/views/view-report.njk
GDS removed the standard Open in new tab Icon. They said that words where more effective.
Also all the nunjucks components are forcing display:block; so this was the best I could do. It's honestly ugly everywhere.
=> Add open in new page button

src/test/v2/cross-browser/saucelabs.conf.ts
N/A
Add bootstrap delay for cross browser tests to prevent admin users being created at same time.
```
[ ] Yes
[x] No
```
=> add bootstrap delay

Jenkinsfile_nightly
N/A
Changing the "nightly" pipeline to start around 1-2pm as a test to see if time of day impacts the reliability of the pipeline.
```
[ ] Yes
[ ] No
```
=> Change "nightly" pipeline to run in the afternoon

config/default.yaml, src/main/app/idam-api/IdamAPI.ts, src/main/controllers/AddPrivateBetaServiceController.ts, src/main/controllers/AddUserDetailsController.ts, src/main/controllers/AddUserRolesController.ts, src/main/interfaces/Role.ts, src/main/interfaces/V2Role.ts, src/main/modules/oidc/index.ts, src/main/utils/roleUtils.ts, src/main/utils/serviceUtils.ts, src/test/unit/test/app/idam-api/IdamAPI.ts, src/test/unit/test/controllers/AddPrivateBetaServiceController.ts, src/test/unit/test/controllers/AddUserDetailsController.ts, src/test/unit/test/controllers/AddUserRolesController.ts, src/test/unit/test/utils/roleUtils.ts, src/test/unit/test/utils/serviceUtils.ts, src/test/unit/utils/mockApi.ts
https://tools.hmcts.net/jira/browse/SIDM-9354
Remove clientAxios by switching v2 get user call to use the *other* client credentials token that dashboard has.
Remove systemAxios by switching to v2 get all roles and using client credentials instead of a password grant.
```
[ ] Yes
[X] No
```
=> SIDM-9354 remove redundant tokens from oidc middleware
